FROM python:3.11-slim

WORKDIR /app

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

RUN apt-get update && apt-get install -y \
    build-essential \
    libpq-dev \
 && rm -rf /var/lib/apt/lists/*

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY app ./app
COPY alembic.ini .
COPY alembic ./alembic

ENV DATABASE_URL=postgresql+psycopg2://riskpulse:riskpulse@postgres:5432/riskpulse

CMD alembic upgrade head && uvicorn app.main:app --host 0.0.0.0 --port 8000
